# Writtten by Muhammed Ali Kaya -  1.04.2026
# DO NOT EDİT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING. THIS FILE IS GENERATED BY THE SYSTEM AND ANY CHANGES MAY BE LOST.

import numpy as np
import cv2
import time
import asyncio
import sys
from mavsdk import System
from mavsdk.telemetry import LandedState
from ultralytics import YOLO
import torch

# Sistem kütüphanelerini tanıt
sys.path.append('/usr/lib/python3/dist-packages')


from gz.transport13 import Node
from gz.msgs10.image_pb2 import Image

model = YOLO("/home/muhammed/yolo_proje/runs/detect/yolov11_sonuclar/egitim/weights/best.pt")

print(torch.cuda.is_available()) # True dönmeli

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Model {device} üzerinde çalışıyor.")

import time

last_save_time = 0


prev_frame_time = 0

def camera_callback(msg):
    global prev_frame_time
    try:
        # 1. Ham veriyi al
        img_data = np.frombuffer(msg.data, dtype=np.uint8)

        # 2. Reshape et 
        raw_frame = img_data.reshape((msg.height, msg.width, 3))

        # 3 Renkleri düzenle
        frame = cv2.cvtColor(raw_frame, cv2.COLOR_RGB2BGR)
        
        # 4. Veriyi kaydet
        #save_data(frame)

        # 5. YOLO tahmini
        results = model.predict(frame, conf=0.4, verbose=False)
        annotated_frame = results[0].plot()
        
        # 6. FPS hesapla
        new_frame_time = time.time()
        fps = 1 / (new_frame_time - prev_frame_time + 1e-6)
        prev_frame_time = new_frame_time

        # 7. FPS'i ekrana yazdır
        cv2.putText(annotated_frame, f"FPS: {int(fps)}", (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        cv2.imshow("VTOL Kamera", annotated_frame)
        cv2.waitKey(1)
    except Exception as e:
        print(f"Hata oluştu: {e}")



async def run_mission(drone):
    print("İHA bekleniyor...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print("İHA bağlandı!")
            break

    print("GPS ve Sistem sağlığı bekleniyor...")
    async for health in drone.telemetry.health():
        if health.is_home_position_ok and health.is_global_position_ok:
            print("Sistem uçuşa hazır!")
            break    
    
    print("-- Arming")
    await drone.action.arm()

    print("-- Takeoff")
    await drone.action.set_takeoff_altitude(80.0)
    await drone.action.takeoff()
    await asyncio.sleep(30) 

    print("-- Mevcut konum alınıyor...")
    # Telemetriden anlık konumu çekiyoruz
    async for position in drone.telemetry.position():
        current_lat = position.latitude_deg
        current_lon = position.longitude_deg
        current_alt = position.relative_altitude_m
        break # Konumu aldık, döngüden çık

    print(f"-- Hedef açılara dönülüyor. Mevcut Konum: {current_lat}, {current_lon}")

    # 90 derece aralıklarla dönerek fotoğraf çek
    for angle in [0, 90, 180, 270]:
        print(f"-- {angle} dereceye dönülüyor...")
        # goto_location(enlem, boylam, yükseklik, yaw_açısı)
        await drone.action.goto_location(current_lat, current_lon, current_alt, angle)
        
        # Dönüşün tamamlanması ve YOLO'nun net kare yakalaması için bekle
        await asyncio.sleep(10)

    print("-- Eve dönülüyor (RTL)...")
    await drone.action.return_to_launch()
    
    print("-- İniş bekleniyor...")
    async for landed_status in drone.telemetry.landed_state():
        if landed_status == LandedState.ON_GROUND:
            print("-- İniş tamamlandı.")
            break 



    await drone.action.disarm()
    print("-- Görev bitti, motorlar kapatılıyor.")
    await asyncio.sleep(2) # Tam kapanma için kısa bir bekleyiş


#def save_data(frame):
    #global last_save_time
    #if frame is None:
        #return
        
    # Klasör yoksa oluştur (Her kontrolde yapmak yerine bir kez yapmak yeterli ama burada güvenli olur)
    #if not os.path.exists('dataset'):
        #os.makedirs('dataset')

    #if time.time() - last_save_time > 0.5: 
        #img_id = int(time.time())
        # Kayıt işlemi
        #cv2.imwrite(f"dataset/car_{img_id}.jpg", frame)
        #last_save_time = time.time()
        #print(f"--- FOTOĞRAF KAYDEDİLDİ: dataset/car_{img_id}.jpg ---")
        #print(f"DEBUG: Frame tipi: {type(frame)}")


async def main():
    drone = System()
    await drone.connect(system_address="udpin://0.0.0.0:14540")

    gz_node = Node()
    topic = "/vtol_camera/image"
    gz_node.subscribe(Image, topic, camera_callback)

    
    # Sadece görevi çalıştırıyoruz
    await run_mission(drone)
    

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nKullanıcı durdurdu.")
    finally:
        # Pencereleri kapat
        cv2.destroyAllWindows()
        print("Sistem kapatıldı.")
